"""empty message

Revision ID: 684433363813
Revises: f7a25da21cad
Create Date: 2025-01-10 22:19:46.198093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684433363813'
down_revision = 'f7a25da21cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
