"""empty message

Revision ID: 95704af12915
Revises: 684433363813
Create Date: 2025-01-12 17:38:16.441274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95704af12915'
down_revision = '684433363813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_question_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isLiked', sa.Integer(), nullable=False),
    sa.Column('isCommented', sa.Integer(), nullable=False),
    sa.Column('isCollected', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_question_status')
    # ### end Alembic commands ###
