"""empty message

Revision ID: e05a13d3de9f
Revises: 95704af12915
Create Date: 2025-01-13 14:43:09.205483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e05a13d3de9f'
down_revision = '95704af12915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_total_view',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('like_t', sa.Integer(), nullable=False),
    sa.Column('comment_t', sa.Integer(), nullable=False),
    sa.Column('collect_t', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('user_question_status', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='当前用户id',
               existing_nullable=True)
        batch_op.drop_index('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question_status', schema=None) as batch_op:
        batch_op.create_index('author_id', ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='当前用户id',
               existing_nullable=True)

    op.drop_table('status_total_view')
    # ### end Alembic commands ###
